server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxxxxx:3306/blog_mybatisplus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  messages:
    basename: i18n/messages

  redis:
    port: 6379
    host: xxxxxxxxxxx

  cloud:
    alicloud:
      access-key: xxxxxxxxxxx
      secret-key: xxxxxxxxxxx
      oss:
        endpoint: xxxxxxxxxxxxx
      bucketName: xxxxxxxxxxxxx



mybatis-plus:
  type-aliases-package: com.zyh.blog     # 取别名
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    root: info                  # springboot本身的日志级别
    com.zyh.blog: debug         # 指定com.zyh.blog包下的日志级别
  file:
    name: log/blog-dev.log      # 指定日志文件的位置

comment.avatar: /images/yaml.jpg     # 自定义评论区的头像
